routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

// auth
Auth::routes();

// categories
Route::resource('/categories', 'CategoryController');
// keywords
Route::resource('/keywords', 'KeywordController');
Route::get('/json-keywords', 'KeywordController@getKeywords')->name('keywords.json');
// articles
Route::resource('/articles', 'ArticleController');

app/Models/Keyword.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Keyword extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];
    
    /**
     * Get related articles
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function keywordArticles()
    {
        return $this->hasMany(KeywordArticle::class);
    }
}

app/Http/Controllers/KeywordController.php
<?php

namespace App\Http\Controllers;

use App\Models\Keyword;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class KeywordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $keywords = Keyword::whereNull('deleted_at')->paginate();
        return view('admin.keywords.index', compact('keywords'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $keyword = new Keyword();
        return view('admin.keywords.form', compact('keyword'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Keyword $keyword)
    {
        $this->validator()->validate();
        DB::beginTransaction();
        try {
            $data['name'] = trim(ucfirst($request->name));
            $keyword->create($data);
            DB::commit();
            
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Keyword has been created'),
                    'data' => $keyword
                ]);
            }
            
            return redirect()->route('keywords.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function show(Keyword $keyword)
    {
        return view('admin.keywords.show', compact('keyword'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function edit(Keyword $keyword)
    {
        return view('admin.keywords.form', compact('keyword'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Keyword $keyword)
    {
        $this->validator()->validate();
        DB::beginTransaction();
        try {
            $data['name'] = trim(ucfirst($request->name));
            $keyword->update($data);
            
            DB::commit();
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Keyword has been updated'),
                    'data' => $keyword
                ]);
            }
            return redirect()->route('keywords.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Keyword  $keyword
     * @return \Illuminate\Http\Response
     */
    public function destroy(Keyword $keyword)
    {
        DB::beginTransaction();
        try {
            $keyword->deleted_at = Carbon::now();
            $keyword->save();
            DB::commit();

            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Keyword has been deleted'),
                    'data' => $keyword
                ]);
            }
            return redirect()->route('keywords.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Get create and update validator
     *
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator()
    {
        $payload = request()->only([
            'name',
        ]);

        return Validator::make($payload, [
            'name'=> 'required|max:100|unique:keywords',
        ]);
    }

    /**
     * Get data json
     * @return \Illuminate\Http\Response
     */
    public function getKeywords(){
        $keywords = Keyword::select('id','name')->whereNull('deleted_at')->get();
        return response()->json($keywords);
    }
}

resources/views/admin/keywords/form.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="content-header m-t-5">
    <h3>
        @if(!empty($keyword->getKey()))
            {{ __("Update Keyword") }}
        @else
            {{ __("Create New Keyword") }}
        @endif
    </h3>
    @include('admin.breadcrumb')
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ !empty($keyword->getKey()) ? route('keywords.update', [$keyword]) : route('keywords.store') }}" method="post">
                @csrf
                @if(!empty($keyword->getKey()))
                    {{ method_field('PATCH') }}
                @endif

                <div class="form-group row">
                    <label for="name" class="col-md-2">{{ __('Name') }}</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="name" id="name" value="{{ old('name') ?? $keyword->name ?? '' }}">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="button-group button-group-form">
                            <a href="{{ action('KeywordController@index') }}" class="btn btn-md btn-secondary">{{ __('Cancel') }}</a>
                            @if(!empty($keyword->getKey()))
                                <button type="submit" class="btn btn-md btn-primary">
                                    {{ __("Update")  }}
                                </button>
                            @else
                                <button type="submit" class="btn btn-md btn-primary">
                                    {{ __("Create")  }}
                                </button>
                            @endif
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@endsection

resources/views/admin/keywords/index.blade.php
@extends('layouts.dashboard')

@section('content')
	<section class="content-header m-t-5">
        <h3>
            {{__("List Keywords")}}
        </h3>
        @include('admin.breadcrumb')
	</section>
	<section class="content">
	    <div class="row">
	        <div class="col-md-12">
                <div class="row">
                    <div class="col-md-10">
                        <form method="GET" action="#">
                            <div class='form-group clearfix'>
                                <div class='col-md-4'>
                                    <div class="input-group custom-search-form">
                                        <input type="text" class="form-control" name="search" placeholder="Search...">
                                        <span class="input-group-btn">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> {{__("Search")}}</button>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-2">
                        <div class='float-right'>
                            <a href="{{ route('keywords.create') }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> {{__("Add")}}</a>
                        </div>
                    </div>
                </div>
                <div class="scroll-x-auto">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{__("No.")}}</th>
                            <th>{{__("Name")}}</th>
                            <th class='text-center'>{{__("Actions")}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($keywords as $i=>$keyword)
                            <tr>
                                <td>{{$i+1}}</td>
                                <td> {{ $keyword->name }} </td>
                                <td class='text-center'>
                                    <div class="btn-group">
                                        <a class="m-r-10" href='{{ route('keywords.edit', [$keyword]) }}'><span class='fas fa-edit'></span></a>		
                                        <a href='{{  route('keywords.show', [$keyword]) }}'><span class="fas fa-eye"></span></a>
                                        <form id="delete_article{{$keyword->id}}" action='{{  route('keywords.destroy', [$keyword]) }}' method="POST">
                                            <input type="hidden" name="_method" value="delete">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <a class="m-l-10" href="#" onclick="document.getElementById('delete_article{{$keyword->id}}').submit();"><span class='fas fa-trash' ></span></a>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
				{{ $keywords->onEachSide(1)->links() }}
			</div>
		</div>
	</section>
@endsection

resources/views/admin/keywords/show.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="content-header m-t-5">
  <h3>
      {{__("Detail Keyword")}}
  </h3>
  @include('admin.breadcrumb')
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <label for="name" class="col-md-2">{{ __('Name') }}</label>
                <div class="col-md-8">
                    {{ $keyword->name }} 
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-md-2"></label>
                <div class="col-md-8">
                    <a href="{{ route('keywords.index') }}" class="btn btn-primary" role="button">{{ __("Back") }}</a>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection