routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

// auth
Auth::routes();

// categories
Route::resource('/categories', 'CategoryController');
// keywords
Route::resource('/keywords', 'KeywordController');
Route::get('/json-keywords', 'KeywordController@getKeywords')->name('keywords.json');
// articles
Route::resource('/articles', 'ArticleController');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'category_id',
        'user_id',
        'updated_by',
        'cover'
    ];

    /**
    * Get related account
    *
    * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
    */
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    /**
     * Get related articles
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function keywordArticles()
    {
        return $this->hasMany(KeywordArticle::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Keyword;
use App\Models\KeywordArticle;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::orderBy('created_at','desc')->paginate();
        return view('admin.articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $article = new Article();
        $categories = Category::select('id','name')->whereNull('deleted_at')->get();
        return view('admin.articles.form', compact('article','categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Article $article)
    {
        $this->validator($article)->validate();
        
        DB::beginTransaction();
        try {
            $dataRequest = $request->only(['title', 'description']);
            if ($request->hasFile('cover')) {
                $file = $request->file('cover');
                $extension = $file->getClientOriginalExtension();
                $dir = 'covers';
                $fileName = Str::random(15) . '.' . $extension;

                $request->cover->storeAs($dir, $fileName, 'public');
                $dataRequest['cover'] = $fileName;
            }
            $dataRequest['category_id'] = $request->category;
            $dataRequest['user_id'] = auth()->id();
            $dataRequest['updated_by'] = auth()->id();
            $newArticle = $article->create($dataRequest);
            
            foreach ($request->keyword as $value) {
                $findKeyword = Keyword::whereRaw('LOWER(name) = ? ',[trim(strtolower($value))])->first();
                if(!empty($findKeyword)){
                    KeywordArticle::updateOrCreate(['keyword_id'=>$findKeyword->id, 'article_id'=>$newArticle->id]);
                }else{
                    $data['name'] = ucfirst($value);
                    $keyword = Keyword::create($data);
                    KeywordArticle::updateOrCreate(['keyword_id'=>$keyword->id, 'article_id'=>$newArticle->id]);
                }
            }

            DB::commit();
            
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Article has been created'),
                    'data' => $article
                ]);
            }
            return redirect()->route('articles.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('admin.articles.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $keywordArticles = KeywordArticle::join('keywords','keywords.id','=','keyword_articles.keyword_id')
        ->select('keywords.id','keywords.name')
        ->where('keyword_articles.article_id', $article->id)
        ->get()->toArray();

        $categories = Category::select('id','name')->whereNull('deleted_at')->get();
        return view('admin.articles.form', compact('article','categories','keywordArticles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $this->validator($article)->validate();
        
        DB::beginTransaction();
        try {
            $dataRequest = $request->only(['title', 'description']);
            if ($request->hasFile('cover')) {
                $file = $request->file('cover');
                $extension = $file->getClientOriginalExtension();
                $dir = 'covers';
                $fileName = Str::random(15) . '.' . $extension;
                storage()->delete($dir . '/' . $article->cover);
                $request->cover->storeAs($dir, $fileName, 'public');
                $dataRequest['cover'] = $fileName;
            }
            $dataRequest['category_id'] = $request->category;
            $dataRequest['updated_by'] = auth()->id();
            $article->update($dataRequest);
            
            if(!empty($request->keyword)){
                KeywordArticle::where('article_id', $article->id)->delete();
                foreach ($request->keyword as $value) {
                    $findKeyword = Keyword::whereRaw('LOWER(name) = ? ',[trim(strtolower($value))])->first();
                    if(!empty($findKeyword)){
                        KeywordArticle::updateOrCreate(['keyword_id'=>$findKeyword->id, 'article_id'=>$article->id]);
                    }else{
                        $data['name'] = ucfirst($value);
                        $keyword = Keyword::create($data);
                        KeywordArticle::updateOrCreate(['keyword_id'=>$keyword->id, 'article_id'=>$article->id]);
                    }
                }
            }

            DB::commit();
            
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Article has been created'),
                    'data' => $article
                ]);
            }
            return redirect()->route('articles.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        DB::beginTransaction();
        try {
            $article->delete();

            DB::commit();
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Article has been deleted'),
                    'data' => $article
                ]);
            }
            return redirect()->route('articles.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Get create and update validator
     *
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator($article)
    {
        $payload = request()->only([
            'title',
            'description',
            'cover',
            'category',
            'keyword',
        ]);

        $data = [
            'title'=> 'required|max:255',
            'description'=> 'required',
            'category'=> 'required|exists:categories,id',
            'keyword'=> 'required|present|array',
        ];

        if(!empty($article->getKey())){
            $data['cover'] = 'image';
        }else{
            $data['cover'] = 'required|image';
        }

        return Validator::make($payload, $data);
    }

    public function getKeywords(Request $request){
        $keywords = Keyword::select('id','name')
        ->whereNull('deleted_at')
        ->where('name', 'like', '%'.$request->get('name').'%')
        ->get();

        return response()->json($keywords);
    }
}

resources/views/admin/articles/form.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="content-header m-t-5">
    <h3>
        @if(!empty($article->getKey()))
            {{ __("Update Article") }}
        @else
            {{ __("Create New Article") }}
        @endif
    </h3>
    @include('admin.breadcrumb')
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ !empty($article->getKey()) ? route('articles.update', [$article]) : route('articles.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                @if(!empty($article->getKey()))
                    {{ method_field('PATCH') }}
                @endif

                <div class="form-group row">
                    <label for="title" class="col-md-2">{{ __('Title') }}</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="title" id="title" value="{{ old('title') ?? $article->title ?? '' }}" placeholder="{{__("Input a title...")}}">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="category" class="col-md-2">{{ __('Category') }}</label>
                    <div class="col-md-8">
                        <select id="category" class="select-category" placeholder="{{__("Select a category...")}}" name="category"> 
                            <option value=""></option>
                            @foreach($categories as $category)
                                <option value="{{$category->id}}" {{ (old('category') ?? $article->category_id ?? '') == $category->id ? 'selected' : '' }}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="cover" class="col-md-2">{{ __('Cover') }}</label>
                    <div class="col-md-8">
                        <div class="input-container">
                            <input type="file" id="real-input" accept="image/jpeg, image/png" class="form-control" name="cover" id="cover" value=""  >
                            <button class="browse-btn">
                                {{__("Browse file")}}
                            </button>
                            <span class="file-info">{{__("Upload a file...")}}</span>
                        </div>
                        <div id="imgPreview" @if(empty($article->cover)) class="d-none" @endif>
                            <img class="col-md-12 img-preview p-initial m-t-10" src="{{ $article->cover ? asset('/storage/covers/'.$article->cover) : '' }}" alt="cover">
                        </div>
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="keyword" class="col-md-2">{{ __('Keyword') }}</label>
                    <div class="col-md-8">
                    <select @if(old('keyword')) data-selected="{{ json_encode(old('keyword')) }}" @elseif(!empty($article->getKey())) data-selected="{{ json_encode($keywordArticles) }}" @endif class="select-keywords" id="keyword" placeholder="{{__("Pick a keyword...")}}" name="keyword[]" value="" multiple></select>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="description" class="col-md-2">{{ __('Description') }}</label>
                    <div class="col-md-8">
                        <textarea class="form-control" name="description" id="description">
                            {!! old('description') ?? $article->description ?? '' !!}
                        </textarea>
                    </div>
                </div>

                <div class="form-group row m-b-10">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="button-group button-group-form">
                            <a href="{{ action('ArticleController@index') }}" class="btn btn-md btn-secondary">{{ __('Cancel') }}</a>
                            @if(!empty($article->getKey()))
                                <button type="submit" class="btn btn-md btn-primary">
                                    {{ __("Update")  }}
                                </button>
                            @else
                                <button type="submit" class="btn btn-md btn-primary">
                                    {{ __("Create")  }}
                                </button>
                            @endif
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@endsection

resources/views/admin/articles/index.blade.php
@extends('layouts.dashboard')

@section('content')
	<section class="content-header m-t-5">
        <h3>
            {{__("List Articles")}}
        </h3>
        @include('admin.breadcrumb')
	</section>
	<section class="content">
	    <div class="row">
	        <div class="col-md-12">
                <div class="row">
                    <div class="col-md-10">
                        <form method="GET" action="#">
                            <div class='form-group clearfix'>
                                <div class='col-md-4'>
                                    <div class="input-group custom-search-form">
                                        <input type="text" class="form-control" name="search" placeholder="Search...">
                                        <span class="input-group-btn">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> {{__("Search")}}</button>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-2">
                        <div class='float-right'>
                            <a href="{{ route('articles.create') }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> {{__("Add")}}</a>
                        </div>
                    </div>
                </div>
                <div class="scroll-x-auto">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{__("No.")}}</th>
                            <th>{{__("Title")}}</th>
                            <th>{{__("Category")}}</th>
                            <th>{{__("Keywords")}}</th>
                            <th class='text-center'>{{__("Actions")}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($articles as $i=>$article)
                            <tr>
                                <td>{{$i+1}}</td>
                                <td> {{ $article->title }} </td>
                                <td> {{ $article->category->name }} </td>
                                <td>
                                    @foreach ($article->keywordArticles as $key=>$item)
                                        {{ $item->keyword->name }}@if($key+1 < $article->keywordArticles->count()),@endif
                                    @endforeach
                                </td>
                                <td class='text-center'>
                                    <div class="btn-group">
                                        <a class="m-r-10" href='{{ route('articles.edit', [$article]) }}'><span class='fas fa-edit'></span></a>		
                                        <a href='{{  route('articles.show', [$article]) }}'><span class="fas fa-eye"></span></a>
                                        <form id="delete_article{{$article->id}}" action='{{  route('articles.destroy', [$article]) }}' method="POST">
                                            <input type="hidden" name="_method" value="delete">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <a class="m-l-10" href="#" onclick="document.getElementById('delete_article{{$article->id}}').submit();"><span class='fas fa-trash' ></span></a>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $articles->onEachSide(1)->links() }}
			</div>
		</div>
	</section>
@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="content-header m-t-5">
  <h3>
      {{__("Detail Article")}}
  </h3>
  @include('admin.breadcrumb')
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <label for="title" class="col-md-2">{{ __('Title') }}</label>
                <div class="col-md-8">
                    <div>{{ $article->title }}</div>
                </div>
            </div>
            <div class="form-group row">
                <label for="category" class="col-md-2">{{ __('Category') }}</label>
                <div class="col-md-8">
                    <div>{{ $article->category->name }}</div>
                </div>
            </div>
            <div class="form-group row">
                <label for="keyword" class="col-md-2">{{ __('Keywords') }}</label>
                <div class="col-md-8">
                    @foreach ($article->keywordArticles as $key=>$item)
                    {{ $item->keyword->name }}@if($key+1 < $article->keywordArticles->count()),@endif
                    @endforeach
                </div>
            </div>
            <div class="form-group row">
                <label for="cover" class="col-md-2">{{ __('Cover') }}</label>
                <div class="col-md-8">
                        <img class="col-md-12 p-initial" src="{{asset('storage/covers/'.$article->cover)}}" alt="cover">
                </div>
            </div>
            <div class="form-group row">
                <label for="description" class="col-md-2">{{ __('Description') }}</label>
                <div class="col-md-8">
                    {!! $article->description !!} 
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-md-2"></label>
                <div class="col-md-8">
                    <a href="{{ route('articles.index') }}" class="btn btn-primary" role="button">{{ __("Back") }}</a>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection