routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', 'HomeController@index')->name('home');

// auth
Auth::routes();

// categories
Route::resource('/categories', 'CategoryController');
// keywords
Route::resource('/keywords', 'KeywordController');
Route::get('/json-keywords', 'KeywordController@getKeywords')->name('keywords.json');
// articles
Route::resource('/articles', 'ArticleController');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
    ];
    
    /**
     * Get related articles
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::whereNull('deleted_at')->paginate();
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = new Category();
        return view('admin.categories.form', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Category $category)
    {
        $this->validator()->validate();
        DB::beginTransaction();
        try {
            $category->create($request->only(['name']));
            
            DB::commit();
            
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Category has been created'),
                    'data' => $category
                ]);
            }
            return redirect()->route('categories.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('admin.categories.form', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->validator()->validate();
        DB::beginTransaction();
        try {
            $category->update($request->only(['name']));
            
            DB::commit();
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Category has been updated'),
                    'data' => $category
                ]);
            }
            return redirect()->route('categories.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        DB::beginTransaction();
        try {
            $category->deleted_at = Carbon::now();
            $category->save();

            DB::commit();
            if (request()->wantsJson()) {
                return response()->json([
                    'message' => __('Category has been deleted'),
                    'data' => $category
                ]);
            }
            return redirect()->route('categories.index');
        } catch (\Exception $exception) {
            DB::rollBack();
            throw $exception;
        }
    }

    /**
     * Get create and update validator
     *
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator()
    {
        $payload = request()->only([
            'name',
        ]);

        return Validator::make($payload, [
            'name'=> 'required|max:100|unique:categories',
        ]);
    }
}

resources/views/admin/categories/form.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="content-header m-t-5">
    <h3>
        @if(!empty($category->getKey()))
            {{ __("Update Category") }}
        @else
            {{ __("Create New Category") }}
        @endif
    </h3>
    @include('admin.breadcrumb')
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <form action="{{ !empty($category->getKey()) ? route('categories.update', [$category]) : route('categories.store') }}" method="post">
                @csrf
                @if(!empty($category->getKey()))
                    {{ method_field('PATCH') }}
                @endif

                <div class="form-group row">
                    <label for="name" class="col-md-2">{{ __('Name') }}</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" name="name" id="name" value="{{ old('name') ?? $category->name ?? '' }}">
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <div class="button-group button-group-form">
                            <a href="{{ action('CategoryController@index') }}" class="btn btn-md btn-secondary">{{ __('Cancel') }}</a>
                            @if(!empty($category->getKey()))
                                <button type="submit" class="btn btn-md btn-primary">
                                    {{ __("Update")  }}
                                </button>
                            @else
                                <button type="submit" class="btn btn-md btn-primary">
                                    {{ __("Create")  }}
                                </button>
                            @endif
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.dashboard')

@section('content')
	<section class="content-header m-t-5">
        <h3>
            {{__("List Categories")}}
        </h3>
        @include('admin.breadcrumb')
	</section>
	<section class="content">
	    <div class="row">
	        <div class="col-md-12">
                <div class="row">
                    <div class="col-md-10">
                        <form method="GET" action="#">
                            <div class='form-group clearfix'>
                                <div class='col-md-4'>
                                    <div class="input-group custom-search-form">
                                        <input type="text" class="form-control" name="search" placeholder="Search...">
                                        <span class="input-group-btn">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit"><i class="fa fa-search"></i> {{__("Search")}}</button>
                                            </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="col-md-2">
                        <div class='float-right'>
                            <a href="{{ route('categories.create') }}" class="btn btn-primary"><i class="fas fa-plus-circle"></i> {{__("Add")}}</a>
                        </div>
                    </div>
                </div>
                <div class="scroll-x-auto">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{{__("No.")}}</th>
                            <th>{{__("Name")}}</th>
                            <th class='text-center'>{{__("Actions")}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $i=>$category)
                            <tr>
                                <td>{{$i+1}}</td>
                                <td> {{ $category->name }} </td>
                                <td class='text-center'>
                                    <div class="btn-group">
                                        <a class="m-r-10" href='{{ route('categories.edit', [$category]) }}'><span class='fas fa-edit'></span></a>		
                                        <a href='{{  route('categories.show', [$category]) }}'><span class="fas fa-eye"></span></a>
                                        <form id="delete_article{{$category->id}}" action='{{  route('categories.destroy', [$category]) }}' method="POST">
                                            <input type="hidden" name="_method" value="delete">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <a class="m-l-10" href="#" onclick="document.getElementById('delete_article{{$category->id}}').submit();"><span class='fas fa-trash' ></span></a>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
				{{ $categories->onEachSide(1)->links() }}
			</div>
		</div>
	</section>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.dashboard')

@section('content')
<section class="content-header m-t-5">
  <h3>
      {{__("Detail Category")}}
  </h3>
  @include('admin.breadcrumb')
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="form-group row">
                <label for="name" class="col-md-2">{{ __('Name') }}</label>
                <div class="col-md-8">
                    {{ $category->name }} 
                </div>
            </div>
            <div class="form-group row">
                <label for="" class="col-md-2"></label>
                <div class="col-md-8">
                    <a href="{{ route('categories.index') }}" class="btn btn-primary" role="button">{{ __("Back") }}</a>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection